### ISSUE TITLE
upgrade to phoenix 1.4

### ISSUE THREAD

**Issue by happysalada** [sasa1977/site_encrypt#19]
upgrading to the latest phoenix version (plug_cowboy too), I get the following warning
```
warning: using :acceptors in options is deprecated. Please pass :num_acceptors to the :transport_options keyword list instead
  (plug_cowboy) lib/plug/cowboy.ex:263: anonymous fn/3 in Plug.Cowboy.to_args/5
  (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
  (plug_cowboy) lib/plug/cowboy.ex:262: Plug.Cowboy.to_args/5
  (plug_cowboy) lib/plug/cowboy.ex:163: Plug.Cowboy.child_spec/1
  (site_encrypt) lib/acme_server/standalone.ex:8: AcmeServer.Standalone.child_spec/1
  (site_encrypt) lib/site_encrypt/phoenix.ex:14: SiteEncrypt.Phoenix.start_link/1
  (stdlib) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
  (stdlib) supervisor.erl:1157: :supervisor.children_map/4
  (stdlib) supervisor.erl:315: :supervisor.init_children/2
  (stdlib) gen_server.erl:374: :gen_server.init_it/2
  (stdlib) gen_server.erl:342: :gen_server.init_it/6
  (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

```
I don't think fixing it is hard. If you're interested, I can have a look at a PR for the upgrade. If you think it's a little early, feel free to close this issue.

**Comment by sasa1977** [comment]
This will be fixed in #17, but it's not yet merged.

**Comment by Qqwy** [comment]
I think this can be closed, based on https://github.com/sasa1977/site_encrypt/pull/17#issuecomment-624267795

**Comment by sasa1977** [comment]
Thanks for pointing out! Yeah, this has been resolved with the recent changes.
