### ISSUE TITLE
Native client hides errors

### ISSUE THREAD

**Issue by ruslandoga** [sasa1977/site_encrypt#64]
👋 

Right now if an error happens with the native client the errors are not shown.

```
plausible-1 | 08:39:43.256 [error] Task #PID<0.4586.0> started from #PID<0.4369.0> terminating
plausible-1 | ** (MatchError) no match of right hand side value: {:error, #SiteEncrypt.Acme.Client.API.Session<https://acme-staging-v02.api.letsencrypt.org/directory>}
plausible-1 |     (site_encrypt 0.6.0) lib/site_encrypt/acme/client.ex:74: SiteEncrypt.Acme.Client.process_new_order/3
plausible-1 |     (site_encrypt 0.6.0) lib/site_encrypt/acme/client.ex:45: SiteEncrypt.Acme.Client.create_certificate/2
plausible-1 |     (site_encrypt 0.6.0) lib/site_encrypt/certification/native.ex:52: SiteEncrypt.Certification.Native.create_certificate/2
plausible-1 |     (site_encrypt 0.6.0) lib/site_encrypt/certification/job.ex:15: SiteEncrypt.Certification.Job.certify/1
```

Thoughts on raising instead of returning an error tuple and causing a MatchError?

**Comment by sasa1977** [comment]
The error info here is definitely not useful, but the problem is that it's not completely clear which error to return here. This is a call to the internal `poll` function which polls the server until it gets the successful result. If this doesn't happen after awhile, it gives up. So the error wouldn't give you much clues, because the error is basically, we didn't get success in the given time. We could perhaps collect all errors, and then somehow hand it off to the app code, though I'm not exactly sure how would I do that. Perhaps introducing some callback for reporting errors.
